src/jukugo_game/account/urls.py
from django.urls import path

from . import views

app_name = "account"
urlpatterns = [
    # log in
    path("", views.SuperLoginView.as_view(), name="login"),
    path("user_id=<int:pk>/", views.SuperUserView.as_view(), name="user"),
]

src/jukugo_game/config/urls.py
from account import views
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.IndexView.as_view(), name="home"),
    # sign up
    path("signup/", views.SignupView.as_view(), name="signup"),
    # log out
    path("logout/", views.SuperLogoutView.as_view(), name="logout"),
    path("account/", include("account.urls")),
    path("game/user_id=<int:pk>/", include("game.urls")),
]

src/jukugo_game/game/urls.py
from django.urls import path

from . import views

app_name = "game"
urlpatterns = [
    path("", views.GameStartView.as_view(), name="start"),
    path("detail/", views.GameDetailView.as_view(), name="detail"),
    path("<str:level>/", views.GamePlayView.as_view(), name="play"),
    path("<str:level>/win/", views.GameWinView.as_view(), name="win",),
    path("<str:level>/lose/", views.GameLoseView.as_view(), name="lose"),
]

src/jukugo_game/jukugo_game/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.mysite.urls")),
    path("game/", include("apps.game.urls")),
]

src/jukugo_game/apps/game/forms.py
from django import forms

from .models import Jukugo


class JukugoForm(forms.ModelForm):
    class Meta:
        model = Jukugo
        app_label = "jukugo"
        fields = "jukugo"

src/jukugo_game/game/forms.py
from typing import Tuple

from django import forms

from .models import Computer, Player


class JukugoForm(forms.ModelForm):
    class Meta:
        model = Player
        app_label = "game"
        fields = ("jukugo",)


class LevelChoiceForm(forms.Form):
    choices: Tuple[Tuple[str, str], ...] = (
        (1, "easy"),
        (2, "normal"),
        (3, "hard"),
        (4, "master"),
    )
    level = forms.fields.ChoiceField(
        choices=choices,
        initial=2,
        required=True,
        label="難易度",
        widget=forms.Select(attrs={"class": "form-control", "id": "difficulty"}),
    )

    class Meta:
        model = Computer
        app_label = "game"
        fields = ("level",)

    def get_name(self, choice: str = 1):
        items = self.choices
        for k, v in items:
            if int(choice) == k:
                return v

src/jukugo_game/game/views.py
from typing import Any, Dict, List, Optional, Tuple, TypeVar

from account.models import SpecialUser
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy

# Create your views here.
from django.views.generic import ListView, TemplateView

from .forms import JukugoForm, LevelChoiceForm
from .jukugo.main import first, get_comment, get_unused_jukugo, step, write
from .jukugo.questions.state import State
from .models import AbstractGamePlayer, Computer, Play, Player

_A = TypeVar("_A", bound=AbstractGamePlayer)
_QS = TypeVar("_QS", bound=QuerySet)


class GameStartView(TemplateView):
    template_name: str = "game/game_start.html"
    context_object_name: str = "play"
    model = Play

    @property
    def account(self) -> SpecialUser:
        pk: int = self.kwargs["pk"]
        return SpecialUser.objects.get(pk=pk)

    @property
    def current_game(self) -> Optional[_A]:
        account: SpecialUser = self.account
        games: _QS = account.play.all()
        return games.last()

    def _get_url(self, kwargs: Dict[str, Any]) -> str:
        if self._level_defined(kwargs):
            return "game:play"
        else:
            return "game:start"

    def _level_defined(self, kwargs: Dict[str, Any]) -> bool:
        return "level" in kwargs

    def _get_attrs(self) -> Dict[str, Any]:
        kwargs: Dict[str, Any] = {"pk": self.request.user.pk}
        # TODO 便宜上最後のユーザーを取り出してるけど、セキュアにはIDで取り出すのが良さそう(OBJECT.get(id=specified_id))
        level: str = self.current_game.level
        if level is not None:
            kwargs.update(level=level)
        return kwargs

    def get_success_url(self) -> str:
        kwargs: Dict[str, Any] = self._get_attrs()
        url: str = self._get_url(kwargs)
        return reverse(url, kwargs=kwargs)

    def get(
        self, request: HttpRequest, *args: Tuple[Any, ...], **kwargs: Dict[str, Any]
    ) -> HttpResponse:
        # これでプルダウン型のレベル調整を可能にする <- いらない
        form: LevelChoiceForm = LevelChoiceForm()
        context: Dict[str, LevelChoiceForm] = {"level": form}
        return render(request, self.template_name, context)

    def create_game(self, request: HttpRequest, form: LevelChoiceForm) -> None:
        # post の name 属性で絞り込み
        selected_level: str = request.POST.get("level")
        # これ綺麗な書き方ありそうだけど知らない
        level: str = form.get_name(selected_level)
        # form経由でなく、modelから直接セーブする方が好き
        start_state: State = first(first="computer", cpu_level=level, jukugo=None)
        Play.create_game(
            account=self.account,
            cpu_level=level,
            start_jukugo=start_state.obs["jukugo"],
        )

    def redirect(self) -> HttpResponseRedirect:
        url: str = self.get_success_url()
        return redirect(url)

    def _post(self, request: HttpRequest) -> None:
        form: LevelChoiceForm = LevelChoiceForm(request.POST)
        if form.is_valid():
            # オブジェクトの保存
            self.create_game(request, form)

    def post(
        self, request: HttpRequest, *args: Tuple[Any, ...], **kwargs: Dict[str, Any]
    ) -> HttpResponseRedirect:
        if request.method == "POST":
            self._post(request)
        # 保存したらURL作ってリダイレクトが直感的で楽
        # formタグ内のbuttonタグからリダイレクトってどうするんじゃろ
        return self.redirect()


class GamePlayView(TemplateView):
    template_name: str = "game/game_play.html"
    context_object_name: str = "play"
    model: Play = Play

    players: Dict[str, _A] = {"player": Player, "computer": Computer}

    @property
    def account(self) -> SpecialUser:
        pk: int = self.kwargs["pk"]
        return SpecialUser.objects.get(pk=pk)

    @property
    def current_game(self) -> Optional[_A]:
        account: SpecialUser = self.account
        games: _QS = account.play.all()
        return games.last()

    @property
    def num_rally(self) -> int:
        game: Play = self.current_game
        return int(game.num_rally)

    @property
    def current_answerer_is_player(self) -> bool:
        game: Play = self.current_game
        return not game.answerer

    def step_game(self, request: HttpRequest, form: JukugoForm) -> bool:
        game: Play = self.current_game

        # playerを更新
        given_jukugo: str = request.POST.get("jukugo")
        cpu_level: str = self.kwargs["level"]
        state: State
        kwargs: Dict[str, Any] = {}

        for name in ["player", "computer"]:
            if "computer" in name:
                given_jukugo = step(name, cpu_level)
                kwargs.update(level=cpu_level)
            state = write(given_jukugo, name, cpu_level)
            kwargs.update(game=game, is_done=state.done)
            player: _A = self.players[name](**kwargs, **state.obs)
            player.save(force_insert=True)
            game.increment(**state.obs)
            given_jukugo = state.obs["jukugo"]
            if game.is_done:
                return True
            kwargs = {}

        return False

    def _get_attrs(self) -> Dict[str, Any]:
        kwargs: Dict[str, Any] = {"pk": self.request.user.pk}
        level: str = self.current_game.level
        if level is not None:
            kwargs.update(level=level)
        return kwargs

    def redirect(self) -> HttpResponseRedirect:
        url: str = self.get_success_url()
        return redirect(url)

    def get_success_url(self) -> str:
        kwargs: Dict[str, Any] = self._get_attrs()
        url: str = self.get_end_url()
        return reverse(url, kwargs=kwargs)

    def get_end_url(self) -> str:
        self.account.increment()
        if self.current_answerer_is_player:
            return "game:win"
        else:
            return "game:lose"

    def _post(self, request: HttpRequest) -> None:
        form: JukugoForm = JukugoForm(request.POST)
        is_done: bool = False
        if form.is_valid():
            is_done = self.step_game(request, form)

        return is_done

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponseRedirect:
        context: Dict[str.Any] = {}
        is_done: bool = False
        if request.method == "POST":
            is_done = self._post(request)
            context.update(
                current=self._get_jukugo_form(),
                last=self._get_last_jukugo(),
                num_rally=self.num_rally,
            )

        # 初期値=Noneを回避する
        if (is_done) and (self.num_rally > 0):
            return self.redirect()
        else:
            return render(request, self.template_name, context)

    def _get_jukugo_form(self) -> JukugoForm:
        # 熟語の入力フォームを作る
        return JukugoForm()

    def _get_last_jukugo(self) -> str:
        # 直前の相手の熟語を取得する
        game: Play = self.current_game
        if game is not None:
            last: Optional[str] = game.jukugo
            return last
        else:
            return "熟語"


class GameResultView(ListView):
    class Meta:
        abstract = True

    @property
    def account(self) -> SpecialUser:
        pk: int = self.kwargs["pk"]
        return SpecialUser.objects.get(pk=pk)

    @property
    def current_game(self) -> Optional[_A]:
        account: SpecialUser = self.account
        games: _QS = account.play.all()
        return games.last()

    @property
    def defeat_player(self) -> str:
        game: Play = self.current_game
        if game.result == "勝利":
            return "computer"
        else:
            return "player"

    @property
    def defeat_comment(self) -> List[str]:
        defeat: str = self.defeat_player
        cpu_level: str = self.current_game.level
        return get_comment(defeat, cpu_level)

    @property
    def available_jukugo(self) -> List[str]:
        game: Play = self.current_game
        last_jukugo: str = game.computer.all().last().jukugo
        if last_jukugo is None:
            last_jukugo = game.player.all().last().jukugo
        level: str = game.level
        return get_unused_jukugo(
            player="player", cpu_level=level, last_jukugo=last_jukugo
        )

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context: Dict[str, Any] = super().get_context_data(**kwargs)
        game: Play = self.current_game
        context["jukugo_list"] = game.get_jukugo_list()
        context["available_list"] = self.available_jukugo
        context["comments"] = self.defeat_comment
        return context


class GameWinView(GameResultView):
    template_name = "game/game_win.html"
    model = Play
    context_object_name = "play"


class GameLoseView(GameResultView):
    template_name = "game/game_lose.html"
    model = Play
    context_object_name = "play"


class GameDetailView(ListView):
    template_name = "game/game_detail.html"
    model = Play
    context_object_name = "play"
    success_url: str = reverse_lazy("game:detail")

    @property
    def account(self) -> SpecialUser:
        pk: int = self.kwargs["pk"]
        return SpecialUser.objects.get(pk=pk)

    @property
    def all_games(self) -> Optional[_QS]:
        account: SpecialUser = self.account
        return account.play.all()

    @property
    def current_game(self) -> Optional[_A]:
        games: _QS = self.all_games
        return games.last()

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context: Dict[str, Any] = super().get_context_data(**kwargs)
        all_games: Play = self.all_games
        context["game_list"] = [
            (game.pk, game.result, game.num_rally, game.level, game.get_jukugo_list())
            for game in all_games
        ]
        return context

src/jukugo_game/templates/game/game_detail.html
</head>
<style>
    .wrap {
        display: flex;
        overflow-x: scroll;
        overflow-y: scroll;
        height: 400;
        width: 1000;
        border: 1px solid #000;
    }

    .rally {
        display: inline-block;
        vertical-align: top;
        padding: 10px;
        border: 1px solid #999;
    }

    table {
        width: 200;
    }
</style>

<body>
    <h1>
        熟語リレー
    </h1>
    <h2>
        戦歴。
    </h2>
    <h2>
        <a href="{% url 'account:user' pk=user.pk %}">マイページ</a><br>
    </h2>
    <h3>
        <center>
            <caption>ゲーム戦歴(縦横スクロール)</caption>
            <div class="wrap">
                {% for pk, result, rally, level, jukugo_list in game_list %}
                <top>
                    <table border="0">
                        <tr>
                            <td>
                                <table border="1" class="table jukugo-rally">
                                    <caption>
                                        ゲームNo.{{ pk }}: {{ result }}<br>
                                        {{ level }}レベル<br>
                                        ラリー数: {{ rally }}
                                    </caption>
                                    <tbody>
                                        <tr>
                                            <th class="table-primary">
                                                <center>回答者</center>
                                            </th>
                                            <th class="table-primary">
                                                <center>熟語</center>
                                            </th>
                                            <th class="table-primary">
                                                <center>正誤</center>
                                            </th>
                                        </tr>
                                        {% for jukugo in jukugo_list %}
                                        <tr>
                                            <td>
                                                <center>{{ jukugo.0 }}</center>
                                            </td>
                                            <td>
                                                <center>{{ jukugo.1 }}</center>
                                            </td>
                                            <td>
                                                <center>{{ jukugo.2 }}</center>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                    </table>
                </top>
                {% endfor %}
            </div>
        </center>
    </h3>
    <h2>
        <a href="{% url 'logout'%}">ログアウト</a><br>
        <a href="{% url 'home' %}">ホーム</a><br>
    </h2>
</body>

</html>

src/jukugo_game/templates/game/game_lose.html
</head>

<body>
    <h1>
        熟語リレー
    </h1>
    <h2>
        まけ。
    </h2>
    <h3>
        敗因:<br>
        {% for c in comments %}
        {{ c }}<br>
        {% endfor %}
    </h3>
    <h3>
        熟語リスト<br>
        <table border="1" class="table table-condensed">
            <tbody>
                <tr>
                    <th class="table-primary">
                        <center>回答者</center>
                    </th>
                    <th class="table-primary">
                        <center>熟語</center>
                    </th>
                    <th class="table-primary">
                        <center>正誤</center>
                    </th>
                </tr>
                {% for jukugo in jukugo_list %}
                <tr>
                    <td>
                        <center>{{ jukugo.0 }}</center>
                    </td>
                    <td>
                        <center>{{ jukugo.1 }}</center>
                    </td>
                    <td>
                        <center>{{ jukugo.2 }}</center>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </h3>
    <h3>
        他の熟語参考:<br>
        {% for jukugo in available_list %}
        {{ jukugo }},&nbsp;
        {% endfor %}
    </h3>
    <h2>
        <a href="{% url 'game:start' pk=user.pk %}">もう一回やる</a><br>
        <a href="{% url 'account:user' pk=user.pk %}">マイページ</a><br>
        <a href="{% url 'game:detail' pk=user.pk %}">成績</a><br>
        <a href="{% url 'logout'%}">ログアウト</a><br>
        <a href="{% url 'home' %}">ホーム</a><br>
    </h2>
</body>

</html>

src/jukugo_game/templates/game/game_play.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>漢字どりる</title>
</head>

<body name="body">
    <h1 name="rally">
        熟語リレー<br>
        {% if num_rally >= 0 %}
        <center name="jukugo-last">
            ラリー回数: {{ num_rally }}
        </center>
        {% endif %}
    </h1>
    <form action="" method="post" name="current">
        {% if play.jukugo != "" %}
        <h2>
            前の漢字:
            <center name="jukugo-last">
                <big name="jukugo-big">
                    {{ last }}
                </big>
            </center>
        </h2>
        <h3 name="jukugo-input">
            {% csrf_token %}
            {{ current.as_p }}
            <button type="submit" value="{{ request.path }}">提出する</button>
        </h3>
        {% else %}
        <h2>redirecting...</h2>
        {% endif %}
    </form>
    <h2>
        <a href="{% url 'account:user' request.user.pk %}">マイページ</a><br>
        <a href="{% url 'logout'%}">ログアウト</a><br>
    </h2>
</body>

</html>

src/jukugo_game/templates/game/game_start.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>漢字どりる</title>
</head>

<body>
    <h1>
        熟語リレー
    </h1>
    <h2>CPU難易度を選択する</h2>
    <h3>
        <form method="post" action="">
            <select id="difficulty" class="form-control" name="level">
                {% for lv in level %}
                <option value={{ lv }}></option>
                {% endfor %}
                {% csrf_token %}
                <button type="submit" class="btn">
                    決定
                </button>
            </select>
        </form>
    </h3>
    <h2>
        <a href="{% url 'account:user' request.user.pk %}">マイページ</a><br>
        <a href="{% url 'game:detail' pk=user.pk %}">成績</a><br>
        <a href="{% url 'logout'%}">ログアウト</a><br>
    </h2>

</body>

</html>

src/jukugo_game/templates/game/game_win.html
</head>

<body>
    <h1>
        熟語リレー
    </h1>
    <h2>
        かち。
    </h2>
    <h3>
        敵の敗因:<br>
        {% for c in comments %}
        {{ c }}<br>
        {% endfor %}
    </h3>
    <h3>
        熟語リスト<br>
        <table border="1" class="table table-condensed">
            <tbody>
                <tr>
                    <th class="table-primary">
                        <center>回答者</center>
                    </th>
                    <th class="table-primary">
                        <center>熟語</center>
                    </th>
                    <th class="table-primary">
                        <center>正誤</center>
                    </th>
                </tr>
                {% for jukugo in jukugo_list %}
                <tr>
                    <td>
                        <center>{{ jukugo.0 }}</center>
                    </td>
                    <td>
                        <center>{{ jukugo.1 }}</center>
                    </td>
                    <td>
                        <center>{{ jukugo.2 }}</center>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </h3>
    <h3>
        他の熟語参考:<br>
        {% for jukugo in available_list %}
        {{ jukugo }},&nbsp;
        {% endfor %}
    </h3>
    <h2>
        <a href="{% url 'game:start' pk=user.pk %}">もう一回やる</a><br>
        <a href="{% url 'account:user' pk=user.pk %}">マイページ</a><br>
        <a href="{% url 'game:detail' pk=user.pk %}">成績</a><br>
        <a href="{% url 'logout'%}">ログアウト</a><br>
        <a href="{% url 'home' %}">ホーム</a><br>
    </h2>
</body>

</html>

src/jukugo_game/templates/game/index.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title>ユーザー画面</title>
</head>

<body>
    <h1>{{ author }}</h1>
    <h2>{{ game.account_id.user_name }}:{{ game.account_id.id }}</h2>
    <h2><a href="{% url 'game:input_jukugo' account_id.id %}">ゲーム開始</a></h2>
</body>

</html>